# Generated by Django 5.2.7 on 2026-09-30 20:26

import django.core.validators
import django.db.models.deletion
import receipts.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_number', models.CharField(help_text='12 цифр — номер налогоплательщика', max_length=12, verbose_name='ФН')),
                ('document_number', models.CharField(help_text='Номер фискального документа', max_length=10, verbose_name='Номер чека (ФД)')),
                ('fiscal_signature', models.CharField(help_text='Фискальная подпись, 0-9 и A-F', max_length=64, verbose_name='ФП')),
                ('purchase_at', models.DateTimeField(verbose_name='Дата и время покупки')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма')),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Принят'), ('rejected', 'Отклонён')], db_index=True, default='pending', max_length=16, verbose_name='Статус')),
                ('rejection_reason', models.TextField(blank=True, default='', verbose_name='Причина отказа')),
                ('is_winner', models.BooleanField(default=False, verbose_name='Выиграл')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=receipts.models.receipt_photo_path, verbose_name='Фото чека')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата регистрации')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempts', models.PositiveIntegerField(default=1, verbose_name='Попыток отправки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Чек',
                'verbose_name_plural': 'Чеки',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['user', '-created_at'], name='receipts_user_created_idx')],
                'constraints': [models.UniqueConstraint(fields=('fiscal_number', 'document_number', 'fiscal_signature'), name='unique_fiscal_receipt', violation_error_message='Такой чек уже зарегистрирован в акции. Проверьте реквизиты или дождитесь проверки ранее отправленного чека.')],
            },
        ),
    ]
